name: End-to-End Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Install ChromeDriver
      run: npm install --save-dev chromedriver

    - name: Start backend
      run: |
        cd ../backend
        nohup python app.py > backend.log 2>&1 & # Start backend server in the background
        sleep 10 # Allow time for the backend to start

    - name: Start frontend
      run: |
        nohup npm start > frontend.log 2>&1 & # Start frontend React app in the background
        sleep 15 # Allow time for the frontend to start

    - name: Run End-to-End Tests
      run: npm run e2e-test
